[project]
authors = ["Henry Dawson <hdd29@cornell.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "TGT_fresh_env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<4"

[pypi-dependencies]
pandas = ">=2.2.3, <3"
matplotlib = ">=3.10.0, <4"
openpyxl = ">=3.1.5, <4"
